language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

notifications:
  email:
    - remenska@gmail.com

  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false


# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install --upgrade pip"
# command to run tests
script: nosetests
